export const blogContent = {
    hero: {
        title: "Our Digital <span class='text-[#00D4AA]'>Thoughts.</span>",
        description: "Insights, perspectives, and expertise from the Hyniva team on AI, Salesforce, AWS, Microsoft, and the future of enterprise transformation.",
    },
    posts: [
        {
            title: "Prepare Your Salesforce Platform for an Agent-Led Future.",
            date: "Feb 19, 2026",
            tag: "Salesforce",
            image: "/images/Blogs/Optimized/blog-1.png",
            href: "/insights/blog/intelligence-needs-infrastructure-prepare-your-salesforce-platform-for-an-agent-led-future",
        },
        {
            title: "Why Financial Institutions Modernize Experience Cloud with LWR",
            date: "Feb 2, 2026",
            tag: "Salesforce",
            image: "/images/Blogs/Optimized/blog-2.png",
            href: "/insights/blog/why-financial-institutions-are-modernizing-salesforce-experience-cloud-with-lwr",
        },
        {
            title: "Modernizing the Contact Center with Agentforce: Connected Journeys",
            date: "Jan 23, 2026",
            tag: "AI",
            image: "/images/Blogs/Optimized/blog-3.png",
            href: "/insights/blog/modernizing-the-contact-center-with-ai-agents-from-fragmented-interactions-to-connected-journeys",
        },
        {
            title: "Reimagining Loan Applications with Agentforce Voice and Chat",
            date: "Dec 24, 2025",
            tag: "Salesforce",
            image: "/images/Blogs/Optimized/blog-4.png",
            href: "/insights/blog/reimagining-loan-applications-voice-and-chat-take-center-stage-with-agentforce",
        },
        {
            title: "Empowering Credit Unions to Thrive in a Digital Era",
            date: "Apr 14, 2025",
            tag: "Banking",
            image: "/images/Blogs/Optimized/blog-5.png",
            href: "/insights/blog/empowering-credit-unions-to-thrive-in-a-digital-era",
        },
        {
            title: "Hyniva Receives SOC 2 Type II Compliance",
            date: "Apr 1, 2025",
            tag: "Company",
            image: "/images/Blogs/Optimized/blog-6.png",
            href: "/insights/news/hyniva-achieves-soc-2-type-ii-compliance-security-first",
            isNews: true,
        },
        {
            title: "Accelerating Digital Transformation at Credit Unions",
            date: "Mar 12, 2025",
            tag: "Banking",
            image: "/images/Blogs/Optimized/blog-7.png",
            href: "/insights/blog/accelerating-digital-transformation-at-credit-unions",
        },
        {
            title: "Advanced Analytics with Salesforce for Sales and Customer Insights",
            date: "Feb 7, 2025",
            tag: "Salesforce",
            image: "/images/Blogs/Optimized/blog-8.png",
            href: "/insights/blog/leveraging-salesforce-for-advanced-analytics-insights-into-sales-and-customer-behavior",
        },
        {
            title: "Integrating Salesforce with Your Marketing Strategy",
            date: "Jan 29, 2025",
            tag: "Salesforce",
            image: "/images/Blogs/Optimized/blog-9.png",
            href: "/insights/blog/salesforce-for-marketing-integrating-salesforce-with-your-marketing-strategy",
        },
        {
            title: "Salesforce Lightning vs. Classic: Why You Should Switch",
            date: "Jan 27, 2025",
            tag: "Salesforce",
            image: "/images/Blogs/Optimized/blog-10.png",
            href: "/insights/blog/salesforce-lightning-vs-classic-why-you-should-switch",
        },
        {
            title: "Solving Data Integration Challenges with Salesforce Data Cloud",
            date: "Jan 7, 2025",
            tag: "Salesforce",
            image: "/images/Blogs/Optimized/blog-11.png",
            href: "/insights/blog/overcoming-data-integration-challenges-with-salesforce-data-cloud",
        },
        {
            title: "Celebrating Success as a Great Place to Work for the Second Year!",
            date: "Jan 3, 2025",
            tag: "Company",
            image: "/images/Blogs/Optimized/blog-12.png",
            href: "/insights/news/hyniva-celebrating-success-as-a-great-place-to-work-for-the-second-consecutive-year",
            isNews: true,
        },
        {
            title: "Unlock the Future of CRM with the Latest Salesforce Innovations",
            date: "Dec 24, 2024",
            tag: "Salesforce",
            image: "/images/Blogs/Optimized/blog-13.png",
            href: "/insights/blog/unlock-the-future-of-crm-with-the-latest-salesforce-innovations",
        },
        {
            title: "Start Your Salesforce FSC Optimization Journey",
            date: "Dec 17, 2024",
            tag: "Salesforce",
            image: "/images/Blogs/Optimized/blog-14.png",
            href: "/insights/blog/optimizing-salesforce-fsc-future-proofing-your-financial-institution-with-hynivas-expertise",
        },
        {
            title: "The Future of Cloud Computing: AWS Trends",
            date: "Nov 29, 2024",
            tag: "AWS",
            image: "/images/Blogs/Optimized/blog-15.png",
            href: "/insights/blog/the-future-of-cloud-computing-aws-trends",
        },
        {
            title: "Benefits of a Tailored AWS Infrastructure. How Hyniva Can Help",
            date: "Nov 15, 2024",
            tag: "AWS",
            image: "/images/Blogs/Optimized/blog-16.png",
            href: "/insights/news/benefits-of-tailored-aws-infrastructure-how-hyniva-can-help",
            isNews: true,
        },
        {
            title: "Optimizing AWS Infrastructure Costs for Back-Office Capabilities",
            date: "Oct 23, 2024",
            tag: "AWS",
            image: "/images/Blogs/Optimized/blog-17.png",
            href: "/insights/blog/optimizing-aws-infrastructure-costs-for-back-office-capabilities",
        },
        {
            title: "Hyniva's Vision for Salesforce Customer 360 Innovations",
            date: "Oct 14, 2024",
            tag: "Salesforce",
            image: "/images/Blogs/Optimized/blog-18.png",
            href: "/insights/blog/hynivas-vision-for-harnessing-salesforce-customer-360-innovations-for-our-clients",
        },
        {
            title: "Salesforce Unveils Agentforce: A Game-Changer in Customer Service",
            date: "Oct 3, 2024",
            tag: "AI",
            image: "/images/Blogs/Optimized/blog-19.png",
            href: "/insights/blog/salesforce-unveils-agentforce-a-game-changer-in-customer-service",
        },
        {
            title: "Overcoming Business Challenges with Salesforce",
            date: "Sep 18, 2024",
            tag: "Salesforce",
            image: "/images/Blogs/Optimized/blog-20.png",
            href: "/insights/blog/overcoming-business-challenges-with-salesforce",
        },
        {
            title: "AI — Empowering Financial Institutions",
            date: "Sep 16, 2024",
            tag: "AI",
            image: "/images/Blogs/Optimized/blog-21.png",
            href: "/insights/blog/ai-empowering-financial-institutions",
        },
        {
            title: "Hyniva Celebrates the Launch of Its New Branch!",
            date: "Aug 27, 2024",
            tag: "Company",
            image: "/images/Blogs/Optimized/blog-22.jpg",
            href: "/insights/news/hyniva-celebrates-the-launch-of-its-new-branch",
            isNews: true,
        },
        {
            title: "Hyniva Achieves SOC 2 Certification. Reinforcing Trust and Compliance",
            date: "Apr 11, 2024",
            tag: "Company",
            image: "/images/Blogs/Optimized/blog-23.jpeg",
            href: "/insights/news/hyniva-achieves-soc-2-certification",
            isNews: true,
        },
        {
            title: "Generative AI — Why It's a Game Changer",
            date: "Mar 27, 2024",
            tag: "AI",
            image: "/images/Blogs/Optimized/blog-24.jpg",
            href: "/insights/blog/generative-ai-why-its-a-game-changer",
        },
        {
            title: "Perpetually in Motion — The Digital Factory",
            date: "Dec 13, 2023",
            tag: "Technology",
            image: "/images/Blogs/Optimized/blog-25.png",
            href: "/insights/blog/perpetually-in-motion-the-digital-factory",
        },
        {
            title: "Hyniva Becomes a Proud Member of GSAC",
            date: "Dec 13, 2023",
            tag: "Company",
            image: "/images/Blogs/Optimized/blog-26.png",
            href: "/insights/blog/hyniva-is-a-proud-member-of-greater-san-antonio-chamber-of-commerce",
        },
        {
            title: "Hyniva is Officially a \"Great Place to Work\"!",
            date: "Dec 13, 2023",
            tag: "Company",
            image: "/images/Blogs/Optimized/blog-27.png",
            href: "/insights/news/hyniva-is-officially-a-great-place-to-work",
            isNews: true,
        },
    ],
};