export const blogContent = {
    hero: {
        title: "Our Digital <span class='text-[#00D4AA]'>Thoughts.</span>",
        description: "Insights, perspectives, and expertise from the Hyniva team on AI, Salesforce, AWS, Microsoft, and the future of enterprise transformation.",
    },
    posts: [
        {
            title: "Prepare Your Salesforce Platform for an <span class='text-[#3B82F6]'>Agent-Led Future.</span>",
            date: "Feb 19, 2026",
            tag: "Salesforce",
            image: "/images/Blogs/Images/1. IntelligenceNeedsInfrastructure_PrepareYourSalesforcePlatformforanAgent-LedFuture.png",
            href: "https://www.hyniva.com/intelligence-needs-infrastructure-prepare-your-salesforce-platform-for-an-agent-led-future/",
        },
        {
            title: "Why Financial Institutions Modernize Experience Cloud with <span class='text-[#3B82F6]'>LWR</span>",
            date: "Feb 2, 2026",
            tag: "Salesforce",
            image: "/images/Blogs/Images/2. WhyFinancialInstitutionsAreModernizingSalesforceExperienceCloudwithLWR.png",
            href: "https://www.hyniva.com/why-financial-institutions-are-modernizing-salesforce-experience-cloud-with-lwr/",
        },
        {
            title: "Modernizing the Contact Center with Agentforce: <span class='text-[#3B82F6]'>Connected Journeys</span>",
            date: "Jan 23, 2026",
            tag: "AI",
            image: "/images/Blogs/Images/3. ModernizingTheContactCenterWithAgentforce.png",
            href: "https://www.hyniva.com/modernizing-the-contact-center-with-ai-agents-from-fragmented-interactions-to-connected-journeys/",
        },
        {
            title: "Reimagining Loan Applications with <span class='text-[#3B82F6]'>Agentforce Voice and Chat</span>",
            date: "Dec 24, 2025",
            tag: "Salesforce",
            image: "/images/Blogs/Images/4. ReimaginingLoanApplications VoiceandChatTakeCenterStagewithAgentforce.png",
            href: "https://www.hyniva.com/reimagining-loan-applications-voice-and-chat-take-center-stage-with-agentforce/",
        },
        {
            title: "Empowering Credit Unions to Thrive in a <span class='text-[#3B82F6]'>Digital Era</span>",
            date: "Apr 14, 2025",
            tag: "Banking",
            image: "/images/Blogs/Images/5. EmpoweringCreditUnionstoThriveinaDigitalEra .png",
            href: "https://www.hyniva.com/empowering-credit-unions-to-thrive-in-a-digital-era/",
        },
        {
            title: "Hyniva Receives <span class='text-[#3B82F6]'>SOC 2 Type II</span> Compliance",
            date: "Apr 1, 2025",
            tag: "Company",
            image: "/images/Blogs/Images/6. HynivaReceivesSOC2TypeIICompliance.png",
            href: "https://www.hyniva.com/hyniva-achieves-soc-2-type-ii-compliance-security-first/",
        },
        {
            title: "Accelerating <span class='text-[#3B82F6]'>Digital Transformation</span> at Credit Unions",
            date: "Mar 12, 2025",
            tag: "Banking",
            image: "/images/Blogs/Images/7. AcceleratingDigitalTransformationatCreditUnions.png",
            href: "https://www.hyniva.com/accelerating-digital-transformation-at-credit-unions/",
        },
        {
            title: "<span class='text-[#3B82F6]'>Advanced Analytics with Salesforce</span> for Sales and Customer Insights",
            date: "Feb 7, 2025",
            tag: "Salesforce",
            image: "/images/Blogs/Images/8. LeveragingSalesforceforAdvancedAnalytics.png",
            href: "https://www.hyniva.com/leveraging-salesforce-for-advanced-analytics-insights-into-sales-and-customer-behavior/",
        },
        {
            title: "Integrating Salesforce with Your <span class='text-[#3B82F6]'>Marketing Strategy</span>",
            date: "Jan 29, 2025",
            tag: "Salesforce",
            image: "/images/Blogs/Images/9. SalesforceforMarketing.png",
            href: "https://www.hyniva.com/salesforce-for-marketing-integrating-salesforce-with-your-marketing-strategy/",
        },
        {
            title: "Salesforce <span class='text-[#3B82F6]'>Lightning vs. Classic:</span> Why You Should Switch",
            date: "Jan 27, 2025",
            tag: "Salesforce",
            image: "/images/Blogs/Images/10. SalesforceLightningvs.ClassicWhyYouShouldSwitch.png",
            href: "https://www.hyniva.com/salesforce-lightning-vs-classic-why-you-should-switch/",
        },
        {
            title: "Solving Data Integration Challenges with <span class='text-[#3B82F6]'>Salesforce Data Cloud</span>",
            date: "Jan 7, 2025",
            tag: "Salesforce",
            image: "/images/Blogs/Images/11. OvercomingDataIntegrationChallengeswithSalesforceDataCloud.png",
            href: "https://www.hyniva.com/overcoming-data-integration-challenges-with-salesforce-data-cloud/",
        },
        {
            title: "Celebrating Success as a <span class='text-[#3B82F6]'>Great Place to Work</span> for the Second Year!",
            date: "Jan 3, 2025",
            tag: "Company",
            image: "/images/Blogs/Images/12. HynivaCelebratingSuccessasaGreatPlacetoWorkfortheSecondConsecutiveYear.png",
            href: "https://www.hyniva.com/hyniva-celebrating-success-as-a-great-place-to-work-for-the-second-consecutive-year/",
        },
        {
            title: "Unlock the Future of CRM with the Latest <span class='text-[#3B82F6]'>Salesforce Innovations</span>",
            date: "Dec 24, 2024",
            tag: "Salesforce",
            image: "/images/Blogs/Images/13. UnlocktheFutureofCRMwiththeLatestSalesforceInnovations.png",
            href: "https://www.hyniva.com/unlock-the-future-of-crm-with-the-latest-salesforce-innovations/",
        },
        {
            title: "Start Your <span class='text-[#3B82F6]'>Salesforce FSC</span> Optimization Journey",
            date: "Dec 17, 2024",
            tag: "Salesforce",
            image: "/images/Blogs/Images/14. StartYourSalesforceFSCOptimizationJourney.png",
            href: "https://www.hyniva.com/optimizing-salesforce-fsc-future-proofing-your-financial-institution-with-hynivas-expertise/",
        },
        {
            title: "The Future of Cloud Computing: <span class='text-[#3B82F6]'>AWS Trends</span>",
            date: "Nov 29, 2024",
            tag: "AWS",
            image: "/images/Blogs/Images/15.Futureofcloudcomputing.png",
            href: "https://www.hyniva.com/the-future-of-cloud-computing-aws-trends/",
        },
        {
            title: "Benefits of a <span class='text-[#3B82F6]'>Tailored AWS Infrastructure:</span> How Hyniva Can Help",
            date: "Nov 15, 2024",
            tag: "AWS",
            image: "/images/Blogs/Images/16. BenefitsofaTailoredAWSInfrastructure.png",
            href: "https://www.hyniva.com/benefits-of-a-tailored-aws-infrastructure-how-hyniva-can-help/",
        },
        {
            title: "Optimizing AWS Infrastructure Costs for <span class='text-[#3B82F6]'>Back-Office Capabilities</span>",
            date: "Oct 23, 2024",
            tag: "AWS",
            image: "/images/Blogs/Images/17. OptimizingAWSInfrastructureCostsforBack-OfficeCapabilities.png",
            href: "https://www.hyniva.com/optimizing-aws-infrastructure-costs-for-back-office-capabilities/",
        },
        {
            title: "Hyniva's Vision for <span class='text-[#3B82F6]'>Salesforce Customer 360</span> Innovations",
            date: "Oct 14, 2024",
            tag: "Salesforce",
            image: "/images/Blogs/Images/18. Hyniva’svisionforharnessingSalesforceCustomer360Innovationsforourclients.png",
            href: "https://www.hyniva.com/hynivas-vision-for-harnessing-salesforce-customer-360-innovations-for-our-clients/",
        },
        {
            title: "Salesforce Unveils Agentforce: A <span class='text-[#3B82F6]'>Game-Changer</span> in Customer Service",
            date: "Oct 3, 2024",
            tag: "AI",
            image: "/images/Blogs/Images/19. SalesforceUnveilsAgentforce.png",
            href: "https://www.hyniva.com/salesforce-unveils-agentforce-a-game-changer-in-customer-service/",
        },
        {
            title: "Overcoming Business Challenges with <span class='text-[#3B82F6]'>Salesforce</span>",
            date: "Sep 18, 2024",
            tag: "Salesforce",
            image: "/images/Blogs/Images/20. OvercomingBusinessChallengeswithSalesforce.png",
            href: "https://www.hyniva.com/overcoming-business-challenges-with-salesforce/",
        },
        {
            title: "AI — Empowering <span class='text-[#3B82F6]'>Financial Institutions</span>",
            date: "Sep 16, 2024",
            tag: "AI",
            image: "/images/Blogs/Images/21. AI–EmpoweringFinancialInstitutions.png",
            href: "https://www.hyniva.com/ai-empowering-financial-institutions/",
        },
        {
            title: "Hyniva Celebrates the Launch of Its <span class='text-[#3B82F6]'>New Branch!</span>",
            date: "Aug 27, 2024",
            tag: "Company",
            image: "/images/Blogs/Images/22. HynivaCelebratestheLaunchofItsNewBranch.jpg",
            href: "https://www.hyniva.com/hyniva-celebrates-the-launch-of-its-new-branch/",
        },
        {
            title: "Hyniva Achieves <span class='text-[#3B82F6]'>SOC 2 Certification.</span> Reinforcing Trust and Compliance",
            date: "Apr 11, 2024",
            tag: "Company",
            image: "/images/Blogs/Images/23. HynivaachievesSOC2Certification!.jpeg",
            href: "https://www.hyniva.com/hyniva-achieves-soc-2-certification/",
        },
        {
            title: "Generative AI — <span class='text-[#3B82F6]'>Why It's a Game Changer</span>",
            date: "Mar 27, 2024",
            tag: "AI",
            image: "/images/Blogs/Images/24.GenerativeAIWhyit’saGameChanger.jpeg",
            href: "https://www.hyniva.com/generative-ai-why-its-a-game-changer/",
        },
        {
            title: "Perpetually in Motion — <span class='text-[#3B82F6]'>The Digital Factory</span>",
            date: "Dec 13, 2023",
            tag: "Technology",
            image: "/images/Blogs/Images/25. PerpetuallyinMotionTheDigitalFactory.png",
            href: "https://www.hyniva.com/perpetually-in-motion-the-digital-factory/",
        },
        {
            title: "Hyniva Becomes a <span class='text-[#3B82F6]'>Proud Member of GSAC</span>",
            date: "Dec 13, 2023",
            tag: "Company",
            image: "/images/Blogs/Images/26. HynivaisaProudMemberofGSAC.png",
            href: "https://www.hyniva.com/hyniva-is-a-proud-member-of-greater-san-antonio-chamber-of-commerce/",
        },
        {
            title: "Hyniva is Officially a <span class='text-[#3B82F6]'>\"Great Place to Work\"!</span>",
            date: "Dec 13, 2023",
            tag: "Company",
            image: "/images/Blogs/Images/27. HynivaisOfficiallyaGreatPlacetoWork.png",
            href: "https://www.hyniva.com/hyniva-is-officially-a-great-place-to-work/",
        },
    ],
};
