export const caseStudiesContent = {
    hero: {
        title: "Real Results. Proven Impact.",
        subtitle: "From challenge to transformation.",
        description: "Discover how Hyniva enables enterprises to modernize operations and deliver measurable business impact.",
        backgroundImage: "/images/2023/11/section-bg.jpg",
    },
    sectionTitle: "Hyniva In Action",
    studies: [
        {
            title: "Autonomous Lending Experience with <em class='italic text-[#3B82F6] font-serif'>FinXServe & Agentforce</em>",
            image: "/images/Case_Studies/1. AutonomousLendingExperiencewithFinXServeandAgentforce.png",
            description: "Built an AI-driven lending journey that automates document processing, decisioning and approvals.",
            href: "#",
        },
        {
            title: "Faster Loan Processing with <em class='italic text-[#3B82F6] font-serif'>Agentforce Document Intelligence</em>",
            image: "/images/Case_Studies/2. AccelerateLoanProcessingWithAgentforce-PoweredDocumentIntelligence.png",
            description: "Loan applications completed in under 2 minutes with AI-driven document intelligence.",
            href: "#",
        },
        {
            title: "Modernizing Contact Centers with <em class='italic text-[#3B82F6] font-serif'>Intelligent IVR Self-Service</em>",
            image: "/images/Case_Studies/3. ModernizingContactCenterswithIntelligentIVRSelf-Service.png",
            description: "Transformed legacy IVR into a Smart Customer Engagement Interaction System.",
            href: "#",
        },
        {
            title: "Autonomous Freight Operations with <em class='italic text-[#3B82F6] font-serif'>GenAI</em>",
            image: "/images/Case_Studies/4. AutonomousFreightOperationswithGenAI.png",
            description: "Reduced load creation time by 98% and costs by 99.5% using GenAI-driven automation.",
            href: "#",
        },
        {
            title: "LWR Modernization for <em class='italic text-[#3B82F6] font-serif'>High-Performance Experiences</em>",
            image: "/images/Case_Studies/5. LWRModernizationForHigh-PerformanceExperiences.png",
            description: "Improved digital experience performance. 2× faster page loads with Lightning Web Runtime.",
            href: "#",
        },
        {
            title: "Rapid Reverse-Engineered <em class='italic text-[#3B82F6] font-serif'>Website Migration</em>",
            image: "/images/Case_Studies/6. RapidReverse-EngineeredWebsiteMigration.png",
            description: "Delivered a full website migration in 2 months with zero downtime without backend access.",
            href: "#",
        },
        {
            title: "Frictionless Customer Authentication for <em class='italic text-[#3B82F6] font-serif'>Secure Banking</em>",
            image: "/images/Case_Studies/7. FrictionlessCustomerAuthenticationforSecureBanking.png",
            description: "Modernized contact center authentication with Pindrop voice biometrics.",
            href: "#",
        },
        {
            title: "Core Banking Transformation on <em class='italic text-[#3B82F6] font-serif'>Microsoft</em>",
            image: "/images/Case_Studies/8. CoreBankingTransformationonMicrosoft.png",
            description: "50% faster loan approvals and 30% lower costs with Microsoft-led modernization.",
            href: "#",
        },
        {
            title: "Turning Enterprise Data into a <em class='italic text-[#3B82F6] font-serif'>Strategic Intelligence Engine</em>",
            image: "/images/Case_Studies/9. TurningEnterpriseDataintoaStrategicIntelligenceEngine.png",
            description: "Enabled real-time Customer 360 insights with a unified, automated data platform.",
            href: "#",
        },
        {
            title: "AWS-Powered Document <em class='italic text-[#3B82F6] font-serif'>Platform Transformation</em>",
            image: "/images/Case_Studies/10. AWS-PoweredDocumentPlatformTransformation.png",
            description: "Saved $500K annually and improved performance by 5× with serverless AWS modernization.",
            href: "#",
        },
        {
            title: "Data-Driven Campaign Management for <em class='italic text-[#3B82F6] font-serif'>Enterprise Marketing</em>",
            image: "/images/Case_Studies/11. Data-DrivenCampaignManagementforEnterpriseMarketing.png",
            description: "Enabled automated campaign scoring and tracking with a fully data-driven marketing platform.",
            href: "#",
        },
        {
            title: "Modernizing Case Management for a Community Healthcare Provider",
            image: "/images/Case_Studies/12. ModernizingCaseManagementforaCommunityHealthcareProvider.png",
            description: "Streamlined case workflows for real-time visibility, better coordination and efficient service delivery.",
            href: "#",
        },
        {
            title: "Intelligent Service Operations on <em class='italic text-[#3B82F6] font-serif'>Salesforce</em>",
            image: "/images/Case_Studies/13. IntelligentServiceOperationsonSalesforce.png",
            description: "Enabled faster, smarter customer support through unified service operations on Salesforce.",
            href: "#",
        },
        {
            title: "Elevating Member Engagement in <em class='italic text-[#3B82F6] font-serif'>Modern Banking Operations</em>",
            image: "/images/Case_Studies/14. ElevatingDigital MemberEngagementinModernBankingOperations.png",
            description: "Delivered real-time lending and engagement through a unified digital experience platform.",
            href: "#",
        },
        {
            title: "Optimizing Loan Routing and Pre-Qualification with <em class='italic text-[#3B82F6] font-serif'>AI</em>",
            image: "/images/Case_Studies/15. OptimizingLoanRoutingandPre-QualificationwithIntelligentAutomation.png",
            description: "Real-time borrower evaluation and lender routing to improve matches and speed up lending.",
            href: "#",
        },
        {
            title: "Legacy CRM to <em class='italic text-[#3B82F6] font-serif'>Modern Lending Platform</em>",
            image: "/images/Case_Studies/16. LegacyCRMtoModernLendingPlatform.png",
            description: "Rebuilt a legacy CRM into a scalable platform enabling faster and efficient lending operations.",
            href: "#",
        },
        {
            title: "Transforming Claims Operations with a <em class='italic text-[#3B82F6] font-serif'>Scalable Digital Platform</em>",
            image: "/images/Case_Studies/17. TransformingInsuranceClaimsOperationswithaScalableDigitalPlatform.png",
            description: "Unified claims workflows with real-time processing and visibility for faster settlements.",
            href: "#",
        },
        {
            title: "Enterprise CRM Modernization on <em class='italic text-[#3B82F6] font-serif'>Microsoft Cloud</em>",
            image: "/images/Case_Studies/18. EnterpriseCRMModernizationonMicrosoftCloud.png",
            description: "Transformed a legacy CRM into a cloud-native Microsoft ecosystem with zero downtime.",
            href: "#",
        },
        {
            title: "Enabling Zero-Downtime Deployments with <em class='italic text-[#3B82F6] font-serif'>AWS</em>",
            image: "/images/Case_Studies/19. EnablingZero-DowntimeDeploymentswithAWS.png",
            description: "95% less downtime and 70% faster deployments using AWS blue-green strategy.",
            href: "#",
        },
        {
            title: "Scalable Multi-Portal Platform for <em class='italic text-[#3B82F6] font-serif'>Complex Education Workflows</em>",
            image: "/images/Case_Studies/20. EngineeredaScalableMulti-Portal PlatformforComplexEducationWorkflows.png",
            description: "Streamlined academic workflows for real-time visibility and seamless interactions.",
            href: "#",
        },
        {
            title: "Building a Mobile-First, Real-Time <em class='italic text-[#3B82F6] font-serif'>Logistics Platform</em>",
            image: "/images/Case_Studies/21. LogisticsPlatformModernization.png",
            description: "Real-time tracking and fully mobile operations with Microsoft-powered transformation.",
            href: "#",
        },
        {
            title: "Cost-Optimized Document Platform on <em class='italic text-[#3B82F6] font-serif'>AWS</em>",
            image: "/images/Case_Studies/22. Cost-OptimizedDocumentPlatformonAWS.png",
            description: "Reduced costs to zero licensing while scaling document management on AWS.",
            href: "#",
        },
        {
            title: "AI-Powered Customer <em class='italic text-[#3B82F6] font-serif'>Support Automation</em>",
            image: "/images/Case_Studies/23. AI-PoweredCustomerSupportAutomation.png",
            description: "Deployed an AI chatbot to improve response times and reduce support effort.",
            href: "#",
        },
    ],
};
