export const caseStudiesContent = {
    hero: {
        title: "Real Results. Proven Impact.",
        subtitle: "From challenge to transformation.",
        description: "Discover how Hyniva enables enterprises to modernize operations and deliver measurable business impact.",
        backgroundImage: "/images/2023/11/section-bg.jpg",
    },
    sectionTitle: "Hyniva In Action",
    studies: [
        {
            title: "<span class='text-[#3B82F6]'>Autonomous Lending Experience</span> with FinXServe and Agentforce",
            image: "/images/Case_Studies/1. AutonomousLendingExperiencewithFinXServeandAgentforce.png",
            description: "Built an AI-driven lending journey that automates document processing, decisioning and approvals.",
            href: "/insights/case-studies/autonomous-lending-experiences",
        },
        {
            title: "<span class='text-[#3B82F6]'>Instant Loan Processing</span> with Agentforce-Powered Document Intelligence",
            image: "/images/Case_Studies/2. AccelerateLoanProcessingWithAgentforce-PoweredDocumentIntelligence.png",
            description: "Loan applications completed in under 2 minutes with AI-driven document intelligence.",
            href: "/insights/case-studies/instant-loan-processing",
        },
        {
            title: "Modernizing Contact Centers with <span class='text-[#3B82F6]'>Intelligent IVR Self-Service</span>",
            image: "/images/Case_Studies/3. ModernizingContactCenterswithIntelligentIVRSelf-Service.png",
            description: "Transformed legacy IVR into a Smart Customer Engagement Interaction System.",
            href: "/insights/case-studies/intelligent-ivr-self-service",
        },
        {
            title: "<span class='text-[#3B82F6]'>Autonomous Freight Operations</span> with GenAI",
            image: "/images/Case_Studies/4. AutonomousFreightOperationswithGenAI.png",
            description: "Reduced load creation time by 98% and costs by 99.5% using GenAI-driven automation.",
            href: "/insights/case-studies/autonomous-freight-operations",
        },
        {
            title: "<span class='text-[#3B82F6]'>LWR Modernization</span> for High-Performance Experiences",
            image: "/images/Case_Studies/5. LWRModernizationForHigh-PerformanceExperiences.png",
            description: "Improved digital experience performance. 2× faster page loads with Lightning Web Runtime.",
            href: "/insights/case-studies/lwr-modernization",
        },
        {
            title: "Rapid Reverse-Engineered <span class='text-[#3B82F6]'>Website Migration</span>",
            image: "/images/Case_Studies/6. RapidReverse-EngineeredWebsiteMigration.png",
            description: "Delivered a full website migration in 2 months with zero downtime without backend access.",
            href: "/insights/case-studies/a-race-against-time-that-others-refused-to-run",
        },
        {
            title: "<span class='text-[#3B82F6]'>Frictionless Customer Authentication</span> for Secure Banking",
            image: "/images/Case_Studies/7. FrictionlessCustomerAuthenticationforSecureBanking.png",
            description: "Modernized contact center authentication with Pindrop voice biometrics.",
            href: "/insights/case-studies/engineering-secure-authentication-through-pindrop-integration",
        },
        {
            title: "<span class='text-[#3B82F6]'>Core Banking Transformation</span> on Microsoft",
            image: "/images/Case_Studies/8. CoreBankingTransformationonMicrosoft.png",
            description: "50% faster loan approvals and 30% lower costs with Microsoft-led modernization.",
            href: "/insights/case-studies/transforming-core-banking-operations-with-microsoft-innovation",
        },
        {
            title: "Turning Enterprise Data into a <span class='text-[#3B82F6]'>Strategic Intelligence Engine</span>",
            image: "/images/Case_Studies/9. TurningEnterpriseDataintoaStrategicIntelligenceEngine.png",
            description: "Enabled real-time Customer 360 insights with a unified, automated data platform.",
            href: "/insights/case-studies/hynivas-customer-360-insights-solution",
        },
        {
            title: "AWS-Powered <span class='text-[#3B82F6]'>Document Platform Transformation</span>",
            image: "/images/Case_Studies/10. AWS-PoweredDocumentPlatformTransformation.png",
            description: "Saved $500K annually and improved performance by 5× with serverless AWS modernization.",
            href: "/insights/case-studies/hyniva-leverages-aws-half-a-million-dollars-savings-annually",
        },
        {
            title: "<span class='text-[#3B82F6]'>Data-Driven Campaign Management</span> for Enterprise Marketing",
            image: "/images/Case_Studies/11. Data-DrivenCampaignManagementforEnterpriseMarketing.png",
            description: "Automated campaign scoring and tracking with a fully data-driven marketing platform.",
            href: "/insights/case-studies/hyniva-campaign-management",
        },
        {
            title: "<span class='text-[#3B82F6]'>Modernizing Case Management</span> for a Community Healthcare Provider",
            image: "/images/Case_Studies/12. ModernizingCaseManagementforaCommunityHealthcareProvider.png",
            description: "Streamlined case workflows for real-time visibility, better coordination and efficient service delivery.",
            href: "/insights/case-studies/modernizing-case-management-for-a-community-healthcare-provider-stop",
        },
        {
            title: "<span class='text-[#3B82F6]'>Intelligent Service Operations</span> on Salesforce",
            image: "/images/Case_Studies/13. IntelligentServiceOperationsonSalesforce.png",
            description: "Enabled faster, smarter customer support through unified service operations on Salesforce.",
            href: "/insights/case-studies/scaling-service-operations-with-salesforce",
        },
        {
            title: "<span class='text-[#3B82F6]'>Elevating Digital Member Engagement</span> in Modern Banking Operations",
            image: "/images/Case_Studies/14. ElevatingDigital MemberEngagementinModernBankingOperations.png",
            description: "Delivered real-time lending and engagement through a unified digital experience platform.",
            href: "/insights/case-studies/member-experience-transformation-at-a-leading-credit-union",
        },
        {
            title: "<span class='text-[#3B82F6]'>Optimizing Loan Routing</span> and Pre-Qualification with Intelligent Automation",
            image: "/images/Case_Studies/15. OptimizingLoanRoutingandPre-QualificationwithIntelligentAutomation.png",
            description: "Real-time borrower evaluation and lender routing to improve matches and speed up lending.",
            href: "/insights/case-studies/scaling-a-secure-pre-qualification-loan-routing-platform-with-intelligent-automation",
        },
        {
            title: "Legacy CRM to <span class='text-[#3B82F6]'>Modern Lending Platform</span>",
            image: "/images/Case_Studies/16. LegacyCRMtoModernLendingPlatform.png",
            description: "Rebuilt a legacy CRM into a scalable platform enabling faster and efficient lending operations.",
            href: "/insights/case-studies/modernizing-a-legacy-platform",
        },
        {
            title: "<span class='text-[#3B82F6]'>Transforming Claims Operations</span> with a Scalable Digital Platform",
            image: "/images/Case_Studies/17. TransformingInsuranceClaimsOperationswithaScalableDigitalPlatform.png",
            description: "Unified claims workflows with real-time processing and visibility for faster settlements.",
            href: "/insights/case-studies/transforming-insurance-claims-operations-with-a-scalable-digital-platform",
        },
        {
            title: "<span class='text-[#3B82F6]'>Enterprise CRM Modernization</span> on Microsoft Cloud",
            image: "/images/Case_Studies/18. EnterpriseCRMModernizationonMicrosoftCloud.png",
            description: "Transformed a legacy CRM into a cloud-native Microsoft ecosystem with zero downtime.",
            href: "/insights/case-studies/empowering-enterprises-through-microsoft-powered-modernization",
        },
        {
            title: "Enabling <span class='text-[#3B82F6]'>Zero-Downtime Deployments</span> with AWS",
            image: "/images/Case_Studies/19. EnablingZero-DowntimeDeploymentswithAWS.png",
            description: "95% less downtime and 70% faster deployments using AWS blue-green strategy.",
            href: "/insights/case-studies/blue-green-deployment-boosting-efficiency-resilience",
        },
        {
            title: "<span class='text-[#3B82F6]'>Engineered a Scalable Multi-Portal Platform</span> for Complex Education Workflows",
            image: "/images/Case_Studies/20. EngineeredaScalableMulti-Portal PlatformforComplexEducationWorkflows.png",
            description: "Streamlined academic workflows for real-time visibility and seamless interactions.",
            href: "/insights/case-studies/scaling-a-multi-portal-education-platform-with-zero-defect-delivery",
        },
        {
            title: "Building a Mobile-First, <span class='text-[#3B82F6]'>Real-Time Logistics Platform</span>",
            image: "/images/Case_Studies/21. LogisticsPlatformModernization.png",
            description: "Real-time tracking and fully mobile operations with Microsoft-powered transformation.",
            href: "/insights/case-studies/logistics-platform-modernization-with-microsoft",
        },
        {
            title: "Cost-Optimized <span class='text-[#3B82F6]'>Document Platform</span> on AWS",
            image: "/images/Case_Studies/22. Cost-OptimizedDocumentPlatformonAWS.png",
            description: "Reduced costs to zero licensing while scaling document management on AWS.",
            href: "/insights/case-studies/aws-enabled-efficiency-transforming-document-management",
        },
        {
            title: "<span class='text-[#3B82F6]'>AI-Powered Customer Support</span> Automation",
            image: "/images/Case_Studies/23. AI-PoweredCustomerSupportAutomation.png",
            description: "Deployed an AI chatbot to improve response times and reduce support effort.",
            href: "/insights/case-studies/ai-hynivas-innovative-solutions",
        },
    ],
};